# Generated by Django 5.2.7 on 2025-10-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
