# Generated by Django 5.2.7 on 2025-10-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintable',
            old_name='table',
            new_name='user_type',
        ),
    ]
